services:
  mysql:
    image: mysql:8.4
    container_name: jobportal-mysql
    environment:
      MYSQL_DATABASE: jobportal
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: jobportal123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - jobportal-data:/var/lib/mysql
volumes:
  jobportal-data:
