import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';

const API = 'http://localhost:8080/api';
const emptyJob = { title: '', company: '', location: '', type: 'Full-time', description: '', requirements: '' };

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('launchpad-user') || 'null'));
  const [jobs, setJobs] = useState([]); const [applications, setApplications] = useState([]); const [recruiterJobs, setRecruiterJobs] = useState([]); const [recruiterApplications, setRecruiterApplications] = useState([]); const [selectedJob, setSelectedJob] = useState(null); const [dashboardOpen, setDashboardOpen] = useState(false);
  const [query, setQuery] = useState(''); const [form, setForm] = useState(emptyJob);
  const [authOpen, setAuthOpen] = useState(false); const [register, setRegister] = useState(false); const [openForm, setOpenForm] = useState(false);
  const [authForm, setAuthForm] = useState({ name: '', email: '', password: '', role: 'CANDIDATE', skills: 'java, react, spring boot, mysql, problem solving', githubUrl: '', portfolioUrl: '' });
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const token = user?.token;
  const headers = () => token ? { Authorization: `Bearer ${token}` } : {};

  function normalizeSkillText(value) {
    return (value || '').split(',').map(item => item.trim().toLowerCase()).filter(Boolean);
  }
  function getCandidateSkills(candidate) {
    const skills = normalizeSkillText(candidate?.skills);
    return skills.length ? skills : ['java', 'react', 'spring boot', 'mysql', 'problem solving', 'api'];
  }
  function extractJobSkills(job) {
    const rawText = (job?.requirements || '').toLowerCase();
    const tokens = rawText.split(/[^a-z0-9+#]+/).filter(term => term.length > 2 && !['and', 'the', 'with', 'for', 'your', 'must', 'good', 'have', 'from', 'role', 'years', 'work', 'using', 'into', 'within', 'experience', 'skills', 'strong', 'knowledge', 'understanding', 'team', 'build', 'strongly', 'preferred'].includes(term));
    const fromComma = normalizeSkillText(job?.requirements || '');
    return [...new Set([...tokens, ...fromComma])].filter(Boolean);
  }
  function analyzeSkillGap(job, candidate) {
    const candidateSkills = getCandidateSkills(candidate);
    const requiredSkills = extractJobSkills(job);
    const matched = requiredSkills.filter(skill => candidateSkills.some(candidateSkill => candidateSkill.includes(skill) || skill.includes(candidateSkill)));
    const missing = requiredSkills.filter(skill => !matched.includes(skill));
    const score = requiredSkills.length ? Math.round((matched.length / requiredSkills.length) * 100) : 100;
    return { matched, missing, score };
  }
  function computeFitScore(job, candidate) {
    if (!job?.requirements) return 0;
    const candidateSkills = getCandidateSkills(candidate);
    const requiredTerms = extractJobSkills(job);
    if (!requiredTerms.length) return 100;
    const matched = requiredTerms.filter(term => candidateSkills.some(skill => skill.includes(term) || term.includes(skill))).length;
    return Math.min(98, Math.max(0, Math.round((matched / requiredTerms.length) * 100)));
  }
  function fitLabel(score) {
    if (score >= 80) return 'Excellent match';
    if (score >= 60) return 'Strong match';
    if (score >= 40) return 'Good potential';
    return 'Emerging match';
  }

  async function loadJobs(search = query) { setLoading(true); try { const response = await fetch(`${API}/jobs?query=${encodeURIComponent(search)}`); if (!response.ok) throw new Error(); setJobs(await response.json()); } catch { setError('The API is unavailable. Start the backend and MySQL first.'); } finally { setLoading(false); } }
  async function loadApplications() { if (!token || user.role !== 'CANDIDATE') return; const response = await fetch(`${API}/applications/mine`, { headers: headers() }); if (response.ok) setApplications(await response.json()); }
  async function loadRecruiterDashboard() { if (!token || user.role !== 'RECRUITER') return; const response = await fetch(`${API}/jobs/mine`, { headers: headers() }); if (!response.ok) { setError('Could not load recruiter workspace.'); return; } const ownedJobs = await response.json(); setRecruiterJobs(ownedJobs); if (ownedJobs.length > 0) { const current = selectedJob && ownedJobs.find(job => job.id === selectedJob.id) ? selectedJob : ownedJobs[0]; setSelectedJob(current); const applicationsResponse = await fetch(`${API}/applications/job/${current.id}`, { headers: headers() }); if (applicationsResponse.ok) setRecruiterApplications(await applicationsResponse.json()); } else { setSelectedJob(null); setRecruiterApplications([]); } }
  async function selectRecruiterJob(job) { setSelectedJob(job); const response = await fetch(`${API}/applications/job/${job.id}`, { headers: headers() }); if (response.ok) setRecruiterApplications(await response.json()); }
  async function updateApplicationStatus(id, value) { const response = await fetch(`${API}/applications/${id}/status?value=${value}`, { method: 'PATCH', headers: headers() }); if (!response.ok) { setError('Could not update application status.'); return; } setRecruiterApplications(recruiterApplications.map(application => application.id === id ? { ...application, status: value } : application)); }
  function toggleRecruiterDashboard() { const nextOpen = !dashboardOpen; setDashboardOpen(nextOpen); if (nextOpen) loadRecruiterDashboard(); }
  useEffect(() => { loadJobs(''); }, []); useEffect(() => { loadApplications(); }, [token]);
  function change(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  async function submitAuth(event) { event.preventDefault(); setError(''); const endpoint = register ? 'register' : 'login'; const body = register ? { ...authForm, skills: authForm.skills.trim(), githubUrl: authForm.githubUrl.trim(), portfolioUrl: authForm.portfolioUrl.trim() } : { email: authForm.email, password: authForm.password }; const response = await fetch(`${API}/auth/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) { setError(await response.text() || 'Authentication failed'); return; } const nextUser = await response.json(); localStorage.setItem('launchpad-user', JSON.stringify(nextUser)); setUser(nextUser); setAuthOpen(false); }
  async function submitJob(event) { event.preventDefault(); const response = await fetch(`${API}/jobs`, { method: 'POST', headers: { ...headers(), 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) { setError(await response.text()); return; } setForm(emptyJob); setOpenForm(false); loadJobs(); }
  async function apply(jobId) { if (!user) { setAuthOpen(true); return; } const resume = document.createElement('input'); resume.type = 'file'; resume.accept = '.pdf,.doc,.docx'; resume.onchange = async () => { const data = new FormData(); if (resume.files[0]) data.append('resume', resume.files[0]); const response = await fetch(`${API}/applications/jobs/${jobId}`, { method: 'POST', headers: headers(), body: data }); if (!response.ok) setError(await response.text()); else { setError('Application submitted.'); loadApplications(); } }; resume.click(); }
  function logout() { localStorage.removeItem('launchpad-user'); setUser(null); setApplications([]); }
  return <main>
    <nav><div className="brand"><span className="brand-mark">+</span> launchpad</div><div className="nav-actions">{user ? <><span className="signed-in">{user.name} · {user.role.toLowerCase()}</span>{user.role === 'RECRUITER' && <><button className="outline" onClick={toggleRecruiterDashboard}>{dashboardOpen ? 'Close workspace' : 'Recruiter workspace'}</button><button className="outline" onClick={() => setOpenForm(!openForm)}>{openForm ? 'Close' : 'Post a role'}</button></>}{user.role === 'CANDIDATE' && <button className="outline" onClick={loadApplications}>My applications</button>}<button className="text-button" onClick={logout}>Log out</button></> : <button className="outline" onClick={() => setAuthOpen(true)}>Sign in</button>}</div></nav>
    <section className="hero"><div className="eyebrow">THE NEXT MOVE STARTS HERE</div><h1>Find work that<br /><em>moves you forward.</em></h1><p>One focused place for ambitious people and the teams building what comes next.</p><div className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && loadJobs()} placeholder="Search by role, company, or location" /><button onClick={() => loadJobs()}>Search jobs</button></div></section>
    <section className="content"><div className="section-heading"><div><span className="eyebrow">OPEN POSITIONS</span><h2>Roles worth your attention</h2></div><span className="count">{jobs.length} opportunities</span></div>{error && <div className="notice">{error}</div>}
      {openForm && <form className="publish" onSubmit={submitJob}><div className="section-heading"><h2>Publish a role</h2><span className="count">Recruiter workspace</span></div><div className="form-grid">{[['title','Job title'],['company','Company'],['location','Location']].map(([name, label]) => <input key={name} name={name} value={form[name]} onChange={change} placeholder={label} required />)}<select name="type" value={form.type} onChange={change}><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Remote</option></select><textarea name="description" value={form.description} onChange={change} placeholder="Describe the role" required /><textarea name="requirements" value={form.requirements} onChange={change} placeholder="Key requirements, separated by commas" required /></div><button className="primary" type="submit">Publish role</button></form>}
      {dashboardOpen && user?.role === 'RECRUITER' && <div className="dashboard"><div className="section-heading"><div><span className="eyebrow">RECRUITER WORKSPACE</span><h2>Manage your pipeline</h2></div><button className="text-button" onClick={loadRecruiterDashboard}>Refresh</button></div><div className="dashboard-grid"><div className="owned-jobs"><div className="dashboard-label">YOUR OPEN ROLES · {recruiterJobs.length}</div>{recruiterJobs.length === 0 ? <p className="muted">Publish your first role to start receiving candidates.</p> : recruiterJobs.map(job => <button className={`owned-job ${selectedJob?.id === job.id ? 'selected' : ''}`} key={job.id} onClick={() => selectRecruiterJob(job)}><strong>{job.title}</strong><span>{job.company} · {job.location}</span></button>)}</div><div className="applicant-list"><div className="dashboard-label">APPLICANTS {selectedJob ? `· ${selectedJob.title}` : ''}</div>{!selectedJob || recruiterApplications.length === 0 ? <p className="muted">No applications for this role yet.</p> : recruiterApplications.map(application => <div className="applicant" key={application.id}><div><strong>{application.candidate.name}</strong><span>{application.candidate.username}</span>{(application.candidate.githubUrl || application.candidate.portfolioUrl) && <div className="applicant-links">{application.candidate.githubUrl && <a href={application.candidate.githubUrl} target="_blank" rel="noreferrer">GitHub</a>}{application.candidate.portfolioUrl && <a href={application.candidate.portfolioUrl} target="_blank" rel="noreferrer">Portfolio</a>}</div>}</div><select value={application.status} onChange={event => updateApplicationStatus(application.id, event.target.value)}><option>APPLIED</option><option>REVIEWING</option><option>INTERVIEW</option><option>REJECTED</option><option>HIRED</option></select></div>)}</div></div></div>}
      {user?.role === 'CANDIDATE' && <div className="profile-proof"><div className="section-heading"><h2>Profile proof</h2></div><div className="profile-links">{user.githubUrl ? <a href={user.githubUrl} target="_blank" rel="noreferrer">GitHub profile</a> : null}{user.portfolioUrl ? <a href={user.portfolioUrl} target="_blank" rel="noreferrer">Portfolio</a> : null}{!user.githubUrl && !user.portfolioUrl && <span className="muted">Add GitHub and portfolio links when you create your account to showcase project proof.</span>}</div></div>}
      {user?.role === 'CANDIDATE' && applications.length > 0 && <div className="applications"><div className="section-heading"><h2>Your applications</h2><span className="count">{applications.length} submitted</span></div>{applications.map(application => <div className="application" key={application.id}><strong>{application.job.title}</strong><span>{application.job.company}</span><b>{application.status}</b></div>)}</div>}
      {loading ? <div className="empty">Loading opportunities...</div> : jobs.length === 0 ? <div className="empty">No roles match your search yet.</div> : <div className="jobs">{jobs.map(job => { const fitScore = user?.role === 'CANDIDATE' ? computeFitScore(job, user) : null; const skillGap = user?.role === 'CANDIDATE' ? analyzeSkillGap(job, user) : null; return <article className="job" key={job.id}><div className="job-top"><div><span className="type">{job.type}</span><h3>{job.title}</h3><p className="company">{job.company} <span>·</span> {job.location}</p></div><button className="arrow" aria-label="Apply to job" onClick={() => apply(job.id)}>↗</button></div>{fitScore !== null && <div className="job-fit"><span className={`fit-pill ${fitScore >= 80 ? 'strong' : fitScore >= 60 ? 'medium' : 'low'}`}>{fitScore}% fit</span><small>{fitLabel(fitScore)}</small></div>}{skillGap && <div className="job-gap"><div className="gap-row"><span className="gap-label">Matched</span>{skillGap.matched.slice(0, 4).map(skill => <span className="gap-tag matched" key={skill}>{skill}</span>)}</div>{skillGap.missing.length > 0 && <div className="gap-row"><span className="gap-label">Missing</span>{skillGap.missing.slice(0, 3).map(skill => <span className="gap-tag missing" key={skill}>{skill}</span>)}</div>}</div>}<p className="description">{job.description}</p><div className="requirements">{job.requirements.split(',').map(item => <span key={item}>{item.trim()}</span>)}</div>{user?.role === 'CANDIDATE' && <button className="apply" onClick={() => apply(job.id)}>Apply with resume</button>}</article>; })}</div>}
    </section>
    {authOpen && <div className="modal-backdrop"><form className="auth-modal" onSubmit={submitAuth}><button type="button" className="close" onClick={() => setAuthOpen(false)}>×</button><span className="eyebrow">{register ? 'JOIN LAUNCHPAD' : 'WELCOME BACK'}</span><h2>{register ? 'Create your account' : 'Sign in to continue'}</h2>{register && <><input placeholder="Your name" value={authForm.name} onChange={e => setAuthForm({ ...authForm, name: e.target.value })} required /><select value={authForm.role} onChange={e => setAuthForm({ ...authForm, role: e.target.value })}><option value="CANDIDATE">I am looking for work</option><option value="RECRUITER">I am hiring</option></select><input placeholder="Skills (comma separated)" value={authForm.skills} onChange={e => setAuthForm({ ...authForm, skills: e.target.value })} /><input placeholder="GitHub URL (optional)" value={authForm.githubUrl} onChange={e => setAuthForm({ ...authForm, githubUrl: e.target.value })} /><input placeholder="Portfolio URL (optional)" value={authForm.portfolioUrl} onChange={e => setAuthForm({ ...authForm, portfolioUrl: e.target.value })} /></>}<input type="email" placeholder="Email address" value={authForm.email} onChange={e => setAuthForm({ ...authForm, email: e.target.value })} required /><input type="password" placeholder="Password (6+ characters)" value={authForm.password} onChange={e => setAuthForm({ ...authForm, password: e.target.value })} required /><button className="primary" type="submit">{register ? 'Create account' : 'Sign in'}</button><button type="button" className="text-button" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'New here? Create an account'}</button></form></div>}
  </main>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
